### ISSUE TITLE
How to use it in Linux?

### ISSUE THREAD

**Issue by btclinux** [vnau/KeePass2Trezor#2]
Hi! I've tried this plugin in mono and wine environments but expectedly Trezor didn't recognized. Any ideas?
![изображение](https://user-images.githubusercontent.com/43704692/215330645-2d22db5a-142e-4277-9f2f-7c4811477e8f.png)

**Comment by brianddk** [comment]
Can confirm on Ubuntu Jammy (22.04) running under VirtualBox 7.0.8.  To reproduce perform the following:

1. Install Ubuntu under Virtualbox 7.0.8
2. `sudo apt update && sudo apt install gcc make perl build-essential` for guest extensions
3. Select "Insert Guest Extensions" under "Tools" menu from your VM to install extensions
4. Install the [Extension Pack](https://www.virtualbox.org/wiki/Downloads#VirtualBox7.0.8OracleVMVirtualBoxExtensionPack) for better USB support
5. Attach your Trezor in the ***USB*** submenu under the ***Devices*** menu
6. As root, copy ***Keepass2Trezor*** folder to `/usr/lib/keepass2/Plugins/`

As a workaround you can use `OtpKeyProv` with Trezor.  The setup is described in the ***Keepass2 with OTP*** section of the following post:

https://www.reddit.com/r/TREZOR/comments/13ayybc

**Comment by brianddk** [comment]
> Might also try running Trezor.NET to see if similar issues present.

I verified that the @MelbourneDeveloper `Trezor.Net` project also fails under MONO.  I'll try to write a cleaner issue on the upstream project when I can.  For now there is this:

https://github.com/MelbourneDeveloper/Trezor.Net/issues/44#issuecomment-1550779746

**Comment by vnau** [comment]
**Trezor.Net** generally supports Linux via [LibUsbDotNet](/LibUsbDotNet/LibUsbDotNet), but there is a bug MelbourneDeveloper/Trezor.Net#45 because of which actually it does not work.

I did some successful tests running it under **MONO** and have thoughts of a workaround and hopefully will find some time to implement it in **Keepass2Trezor** in the near future.
