### ISSUE TITLE
Is Trezor Model T supported?

### ISSUE THREAD

**Issue by vnau** [vnau/KeePass2Trezor#5]
Although the **Trezor.Net** library used in the project supports **Model T** and the process is almost the same as for **Model One**, I have no ability to check if **KeePass2Trezor** actually works with with it smoothly.

It would be great if someone could confirm/deny the possibility of working with **Model T** and describe the problems that have arisen, if any.

**Comment by btclinux** [comment]
Checked with Trezor model T in Linux. Working without issues

**Comment by vnau** [comment]
Thanks for the confirmation, really good to know about it!
